### ISSUE TITLE
4,096 character limitation

### ISSUE THREAD

**Issue by vertigo220** [m417z/Textify#10]
I just used this to copy a big error message, but it will only show (and therefore allow me to copy) the first 4,096 characters. Due to that very specific number, and the fact it ended abruptly in the middle of a line, I can only assume it's a limitation based on characters vs something else. In case it matters, the dialog was an error message when trying to run Borderlands 1 via Steam, and it has the Borderlands icon, though no other distinguishing features.

**Comment by m417z** [comment]
The limit is imposed by the target program, not Textify.
See the discussion here: https://rammichael.com/textify/comment-page-3#comment-8942

Quoting the relevant part:

Q:

> Is there any ‘number of characters’ limit to this? Currently I see a maximum of 4100 characters copied to windows clipboard. What if I have to copy an entire web-page having about 15000 characters? Can this functionality be added? or Is it possible to modify the source code?

A:

> Not in Textify. Textify uses the UI Automation API, and usually the target application, which provides text via this API, limits the length. For example, you can try and see that Notepad has a different limit than Chrome.
