### ISSUE TITLE
Feature request: Add program/process exclusions under Advanced Settings

### ISSUE THREAD

**Issue by e-t-l** [m417z/Textify#12]
One feature that could make this a bit more convenient, especially if a more common mouse shortcut is used, would be to put a section in Advanced Settings where users could enter programs and/or processes that should be ignored by Textify, like a blacklist.

For example, if I want my mouse shortcut to be ctrl + middle-click, but there's one other program (Photoshop) that also uses this keyboard+mouse combination, and I'm confident I will never need to use Textify _on_ Photoshop (because everything in PS is copy-able already), then I could add Photoshop to my Textify blacklist. That way, ctrl + middle click would trigger Textify in all other programs, but would _not_ trigger Textify when used in Photoshop.

Would this be feasible?

**Comment by m417z** [comment]
Done, please try the newly released v1.8.5.
Usage:
```ini
[exclude]
1=photoshop.exe
2=notepad.exe
```

**Comment by e-t-l** [comment]
Wow, that was super fast, thanks!
