### ISSUE TITLE
Quotation mark issues in `command=`

### ISSUE THREAD

**Issue by GH01** [m417z/Textify#14]
1.
`command=%rs` or `command="%rs"`

If the string contains a space, like: `D:\my folder\app.exe`

Textify Error:
```
An error occurred while trying to execute the following command:
%rs
```

BTW, please show the error part of the string (e.g. `D:\my`) in the message, rather than just show `%rs` as above.

---
2.
`command="D:\my folder\app.exe" "%rs"`

Textify Error:
```
An error occurred while trying to execute the following command:
D:\my folder\app.exe" "%rs
```

`command=` should support 2 or more pairs of quotation marks, because paths/parameters could contain spaces.

**Comment by m417z** [comment]
Due to the format of the ini file, you need to use quotes twice. For example:
`command=""%rs""`
`command=""D:\my folder\app.exe" "%rs""`

See also:
https://ramensoftware.com/textify/comment-page-4#comment-12808
