### ISSUE TITLE
Suggestion: Support app icons

### ISSUE THREAD

**Issue by GH01** [m417z/Textify#15]
`icon=D:\my folder\app.exe`
`icon=D:\my folder\app.exe, 2`

or if it's a system app:
`icon=explorer.exe`

**Comment by m417z** [comment]
Done in v1.10.

**Comment by m417z** [comment]
I'm using a Windows API function for the icon extraction, so it depends on the function.

**Comment by GH01** [comment]
`icon=explorer.exe` doesn't work for me...
It's a Win 7 issue?

**Comment by m417z** [comment]
I tried it on Windows 10 and it doesn't work here too. You can use a full path, or you can use environment variables (`%windir%\explorer.exe`).
