### ISSUE TITLE
Suggestion: Pin button in the text-grabbing window

### ISSUE THREAD

**Issue by GH01** [m417z/Textify#17]
Please add a Pin button in the text-grabbing window (or/and a shortcut key to pin the window), so that one can keep the window open and do multiple tasks:
1) With the window open, I can trigger more than one button during the session (especially when I deal with a selection, not the whole text).
2) I can switch between windows.

**Comment by m417z** [comment]
Done in v1.10, see [this blog post](https://ramensoftware.com/textify-v1-10-with-a-resizable-and-editable-text-popup).

**Comment by GH01** [comment]
> 1. With the window open, I can trigger more than one button during the session (especially when I deal with a selection, not the whole text).

Please consider this.
It's useful when we do multi-search.

Currently, triggering one button will close the window.
