### ISSUE TITLE
Suggestion: Support other apps' grabbing

### ISSUE THREAD

**Issue by GH01** [m417z/Textify#18]
Take [EmEditor](https://www.emeditor.com) as an example. It can grab text from some controls via its tray app (emedtray.exe) by using a hotkey, which is more convenient than the usual steps (Ctrl+C here; Ctrl+V there; and the clipboard content has to be changed.)

However, EmEditor's grabbing fails on Textify window.

Would you please investigate this?

If it's just because Textify window closed too early, I think the implementation of #17 can help.

**Comment by m417z** [comment]
Probably solved with #17, if not, leave a comment and I'll reopen the issue.
