### ISSUE TITLE
Suggestion: Add a simple button to Quit

### ISSUE THREAD

**Issue by popyoung** [m417z/Textify#19]
In most cases, I only use this tool once to grab something. Then I need to quit it. Maybe you should add a simple quit button to the GUI. In fact, if I check the option "hide_tray_icon", it can no longer quit.

**Comment by m417z** [comment]
Added in v1.9.

**Comment by zhugexiaoshang** [comment]
Thank you for your letter！  I've received your letter, I'll reply to you as soon as possible.

**Comment by popyoung** [comment]
Glad to see that.
