### ISSUE TITLE
French Translation: The “Plus de paramètres” message overflows from the button.

### ISSUE THREAD

**Issue by mooms06** [m417z/Textify#29]
See for yourself:

![image](https://github.com/user-attachments/assets/192d6128-6263-418a-a362-0befbf3f65c1)

A quick fix could be to shorten the translation to `Paramètres` or `+ de paramètres`.
Also, the keyboard shortcuts for `Plus de paramètres` and `Quitter` are missing.

In English it's OK:

![image](https://github.com/user-attachments/assets/4a05c326-9aa1-4f83-8355-6ab933c56fe2)

**Comment by m417z** [comment]
Thanks, I applied your suggestions.

![image](https://github.com/user-attachments/assets/337a6ec0-a1ce-469c-9b1e-a6465f08f9b8)

![image](https://github.com/user-attachments/assets/c03e9527-ae43-46e1-8832-7385296f0163)

**Comment by mooms06** [comment]
That was quick !
Thank you.

**Comment by m417z** [comment]
I also added automatic builds on GitHub, so you can grab the executable here to test or use:
https://github.com/m417z/Textify/actions/runs/11111410567

**Comment by mooms06** [comment]
It works fine, thanks.

The keyboard shortcuts only appears once `alt` is pressed, is this an intended feature ?

Before:
![image](https://github.com/user-attachments/assets/94546c1f-0a52-408e-a661-1cdf0db8d5ef)

After pressing Alt:
![image](https://github.com/user-attachments/assets/6eb644b5-cdae-430d-9aa8-22e6e4e9328c)

**Comment by m417z** [comment]
Yes, that's how Windows works. You can read about it here, for example:
https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-create-access-keys?view=netdesktop-8.0

**Comment by mooms06** [comment]
OK, I wasn't aware of that.
