### ISSUE TITLE
Not working in Telgram Desktop

### ISSUE THREAD

**Issue by SmartManoj** [m417z/Textify#6]

**Comment by m417z** [comment]
Textify relies on UI Automation. There’s a tool from Microsoft called Inspect which shows automation-related information. It can be downloaded [here](https://www.dropbox.com/s/5cfa754k000zt07/inspect.exe?dl=1).

Please try it on the text which Textify can’t handle, and let me know whether Inspect is able to extract the text.

It's possible that the Telegram app just doesn't provide accessibility data. Related issue: https://github.com/telegramdesktop/tdesktop/issues/476
