### ISSUE TITLE
Stopped working 

### ISSUE THREAD

**Issue by SmartManoj** [m417z/Textify#7]
![image](https://user-images.githubusercontent.com/7231077/93303586-5c9ec000-f819-11ea-8b27-4fd0ce724186.png)

**Comment by m417z** [comment]
What exactly stopped working? At which point are you experiencing a
problem? Are you getting an error message? Please provide as much
information as possible.

**Comment by SmartManoj** [comment]
Nothing happens when using the shortcuts.

**Comment by m417z** [comment]
It works for me, and no users reported such issues before.
I need a way to reproduce the problem to be able to help you.
If you find any additional clue, such as another conflicting program, please let me know.

**Comment by SmartManoj** [comment]
```
#SingleInstance, force
!RButton::
MsgBox, hi
```

No conflict found using ahk.

**Comment by SmartManoj** [comment]
Can we have a Test button?

**Comment by m417z** [comment]
To test what?
The source code is right here, feel free to compile and step over the code to see where it fails.

**Comment by SmartManoj** [comment]
Is there any logcat equivalent for windows

**Comment by m417z** [comment]
Not for this case, no.

**Comment by SmartManoj** [comment]
Worked after restart.
