### ISSUE TITLE
no auto start at login

### ISSUE THREAD

**Issue by Leunaam** [m417z/Textify#8]
when i turn on the computer, textify does not start automatically.

![Screenshot (19)](https://user-images.githubusercontent.com/70819291/94994153-26da3500-0596-11eb-9dd2-7304c23d1974.png)

**Comment by m417z** [comment]
You can try reinstalling it. Alternatively, you can set it to run at startup manually, e.g. by adding a shortcut to the startup folder. Use the `-hidewnd` command line switch to start Textify hidden.
