### ISSUE TITLE
virustotal detect virus. You can tell me if this is false positive? thanks

### ISSUE THREAD

**Issue by reproteq** [m417z/Textify#9]
https://www.virustotal.com/gui/file/55faaaacc49e916a5d4fdd24e657b80a7cd675c55c16b2ddd936051f1f978d25/detection

Antiy-AVL

Trojan/Win32.Wacatac
SecureAge APEX

Malicious
BitDefenderTheta

Gen:NN.ZexaF.34634.su0@aaA0zbli
Comodo

Malware@#24baayn5oevsc
Cyren

W32/Trojan.MECS-4129
Gridinsoft

Trojan.Win32.Packed.vb
Rising

Trojan.Generic@ML.90 (RDML:dFU7IXLfzEh34hOib7MfDQ)
Lastline

MALWARE

**Comment by m417z** [comment]
Yes, those are false positives. You can contact the relevant companies for a clarification, and you'll find out that the detections are false positives. See also this old, but still relevant blog post: [Antivirus companies cause a big headache to small developers.](http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/)

Of course, you can also just compile the code yourself if you prefer.

**Comment by reproteq** [comment]
oh  yes  iknow this  Antivirus companies cause a big headache to small developers.
Thanks alot mate.
